// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stdDetails.Models;

#nullable disable

namespace stdDetails.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20241003070823_stdDetailsAddStandard")]
    partial class stdDetailsAddStandard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("stdDetails.Models.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StudentAge");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StudentName");

                    b.Property<string>("Standards")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("StudentStandard");

                    b.HasKey("Id");

                    b.ToTable("SecondStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
